<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE jugadores [
        <!ELEMENT jugadores (jugador*)>
        <!ELEMENT jugador (nombre, cartera, passwd)>
        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT cartera (#PCDATA)>
        <!ELEMENT passwd (#PCDATA)>
        ]>
<jugadores>
    <jugador>
        <nombre>u1</nombre>
        <cartera>1000</cartera>
        <passwd></passwd>
    </jugador>
    <jugador>
        <nombre>u2</nombre>
        <cartera>1000</cartera>
        <passwd></passwd>
    </jugador>
    <jugador>
        <nombre>u3</nombre>
        <cartera>1000</cartera>
        <passwd></passwd>
    </jugador>
    <jugador>
        <nombre>u4</nombre>
        <cartera>1000</cartera>
        <passwd></passwd>
    </jugador>
</jugadores>
